# Generated by Django 3.2.5 on 2021-07-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courses_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.courses'),
        ),
        migrations.AddField(
            model_name='order',
            name='Students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.students'),
        ),
    ]
