# Generated by Django 3.2.5 on 2021-07-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210726_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='typecast',
            field=models.ManyToManyField(to='accounts.TypeCast'),
        ),
    ]
