# Generated by Django 3.2.5 on 2021-07-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210726_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
